<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>UpdaterHelper</AssemblyName>
    <RootNamespace>ProtocolBunker.Desktop.UpdateHelper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\app.ico" />
    <AvaloniaResource Include="Assets\app-128x128.png" />
    <EmbeddedResource Include="AsciiAnimations\animation-05.json" />
  </ItemGroup>
</Project>
