<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>UpdaterHelper</AssemblyName>
    <RootNamespace>ProtocolBunker.UpdaterHelper</RootNamespace>
    <ApplicationIcon>..\..\assets\icons\app.ico</ApplicationIcon>
    <Version>0.2.7</Version>
    <FileVersion>0.2.7.0</FileVersion>
    <AssemblyVersion>0.2.7.0</AssemblyVersion>
  </PropertyGroup>
</Project>


