<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ProtocolBunkerSetup</AssemblyName>
    <RootNamespace>ProtocolBunker.Bootstrapper</RootNamespace>
    <ApplicationIcon>..\..\assets\icons\app.ico</ApplicationIcon>
    <Version>0.2.7</Version>
    <FileVersion>0.2.7.0</FileVersion>
    <AssemblyVersion>0.2.7.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Embedded\payload.zip" Condition="Exists('Embedded\payload.zip')" />
  </ItemGroup>
</Project>


